services:
  satisfactory:
    image: sknnr/satisfactory-server:latest
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "15777:15777/udp"
      - "15000:15000/udp"
    environment:
      GAME_PORT: "7777"
      QUERY_PORT: "15777"
      BEACON_PORT: "15000"
    volumes:
      - satisfactory-persistent-data:/home/steam/satisfactory
    stop_grace_period: 90s

volumes:
  satisfactory-persistent-data:
