services:
  satisfactory:
    image: sknnr/satisfactory-server:latest
    ports:
      - "7777:7777/udp"
      - "7777:7777/tcp"
      - "8888:8888/tcp"
    environment:
      GAME_PORT: "7777"
      MESSAGE_PORT: "8888"
    volumes:
      - satisfactory-persistent-data:/home/steam/satisfactory
    stop_grace_period: 90s

volumes:
  satisfactory-persistent-data:
